openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://sunrinthon.herokuapp.com/
paths:
  /api/v1/user:
    post:
      responses:
        '200':
          description: OK